const router  = require("express").Router();
const bcrypt  = require("bcryptjs");
const { pool } = require("../db");
const { adminOnly } = require("../middleware/auth");

const DAYS  = ["Monday","Tuesday","Wednesday","Thursday","Friday"];
const TIMES = "09:00,09:30,10:00,10:30,11:00,11:30,14:00,14:30,15:00,15:30,16:00,16:30";

const SEED_DOCTORS = [
  // ── Cardiologists (10) ──────────────────────────────────────────────────────
  { name:"Dr. Arun Mehta",         specialty:"Cardiologist", department:"Cardiology", qualification:"MBBS, MD, DM Cardiology",             experience:18, fee:800,  rating:4.9, email:"arun.mehta@docapp.com",         bio:"Senior cardiologist with 18 years of experience in interventional cardiology and heart failure management." },
  { name:"Dr. Ramesh Iyer",        specialty:"Cardiologist", department:"Cardiology", qualification:"MBBS, MD, DM Cardiology",             experience:22, fee:900,  rating:4.8, email:"ramesh.iyer@docapp.com",         bio:"Expert in echocardiography and cardiac catheterization with two decades of clinical practice." },
  { name:"Dr. Sunita Rao",         specialty:"Cardiologist", department:"Cardiology", qualification:"MBBS, MD Cardiology",                 experience:14, fee:750,  rating:4.7, email:"sunita.rao@docapp.com",          bio:"Specialises in preventive cardiology and lipid management for high-risk patients." },
  { name:"Dr. Kiran Bose",         specialty:"Cardiologist", department:"Cardiology", qualification:"MBBS, MD, DM Cardiology",             experience:10, fee:700,  rating:4.6, email:"kiran.bose@docapp.com",          bio:"Interventional cardiologist trained at AIIMS with expertise in coronary angioplasty." },
  { name:"Dr. Nilesh Patil",       specialty:"Cardiologist", department:"Cardiology", qualification:"MBBS, MD, FACC",                      experience:16, fee:850,  rating:4.8, email:"nilesh.patil@docapp.com",        bio:"Fellow of the American College of Cardiology specialising in heart rhythm disorders." },
  { name:"Dr. Pooja Menon",        specialty:"Cardiologist", department:"Cardiology", qualification:"MBBS, MD Cardiology",                 experience:9,  fee:650,  rating:4.5, email:"pooja.menon@docapp.com",         bio:"Focused on women's heart health and cardiac rehabilitation programmes." },
  { name:"Dr. Sanjay Kulkarni",    specialty:"Cardiologist", department:"Cardiology", qualification:"MBBS, DM Cardiology",                 experience:20, fee:950,  rating:4.9, email:"sanjay.kulkarni@docapp.com",     bio:"Pioneer in minimally invasive cardiac procedures with over 3000 successful interventions." },
  { name:"Dr. Anand Varma",        specialty:"Cardiologist", department:"Cardiology", qualification:"MBBS, MD, DM Cardiology",             experience:12, fee:780,  rating:4.7, email:"anand.varma@docapp.com",         bio:"Specialises in paediatric cardiology and congenital heart disease management." },
  { name:"Dr. Rekha Shetty",       specialty:"Cardiologist", department:"Cardiology", qualification:"MBBS, MD Cardiology, FESC",           experience:17, fee:820,  rating:4.8, email:"rekha.shetty@docapp.com",        bio:"Fellow of the European Society of Cardiology with expertise in cardiac imaging." },
  { name:"Dr. Deepak Joshi",       specialty:"Cardiologist", department:"Cardiology", qualification:"MBBS, DM Cardiology",                 experience:11, fee:710,  rating:4.6, email:"deepak.joshi@docapp.com",        bio:"Heart failure specialist with extensive experience in device therapy and transplant evaluation." },
  // ── Dermatologists (10) ─────────────────────────────────────────────────────
  { name:"Dr. Priya Sharma",       specialty:"Dermatologist", department:"Dermatology", qualification:"MBBS, MD Dermatology",             experience:12, fee:600,  rating:4.8, email:"priya.sharma@docapp.com",        bio:"Expert in skin disorders, cosmetic dermatology and laser treatments with over a decade of practice." },
  { name:"Dr. Kavya Nair",         specialty:"Dermatologist", department:"Dermatology", qualification:"MBBS, DVD, MD Dermatology",        experience:8,  fee:550,  rating:4.7, email:"kavya.nair@docapp.com",          bio:"Specialises in acne, pigmentation and anti-ageing treatments using advanced laser technology." },
  { name:"Dr. Rohit Gupta",        specialty:"Dermatologist", department:"Dermatology", qualification:"MBBS, MD Dermatology",             experience:15, fee:650,  rating:4.6, email:"rohit.gupta@docapp.com",         bio:"Experienced in treating psoriasis, eczema and autoimmune skin conditions." },
  { name:"Dr. Sneha Pillai",       specialty:"Dermatologist", department:"Dermatology", qualification:"MBBS, MD, DNB Dermatology",        experience:10, fee:580,  rating:4.8, email:"sneha.pillai@docapp.com",        bio:"Cosmetic dermatologist offering PRP therapy, chemical peels and dermal fillers." },
  { name:"Dr. Arjun Das",          specialty:"Dermatologist", department:"Dermatology", qualification:"MBBS, MD Dermatology",             experience:7,  fee:500,  rating:4.5, email:"arjun.das@docapp.com",           bio:"Focused on paediatric dermatology and inherited skin disorders." },
  { name:"Dr. Meera Krishnan",     specialty:"Dermatologist", department:"Dermatology", qualification:"MBBS, DVD, MD Dermatology",        experience:13, fee:620,  rating:4.7, email:"meera.krishnan@docapp.com",      bio:"Expert in hair loss treatment, scalp disorders and trichology." },
  { name:"Dr. Vivek Soni",         specialty:"Dermatologist", department:"Dermatology", qualification:"MBBS, MD Dermatology",             experience:9,  fee:560,  rating:4.6, email:"vivek.soni@docapp.com",          bio:"Specialises in vitiligo, melasma and complex pigmentation disorders." },
  { name:"Dr. Ananya Bhat",        specialty:"Dermatologist", department:"Dermatology", qualification:"MBBS, MD Dermatology, FRCP",       experience:18, fee:700,  rating:4.9, email:"ananya.bhat@docapp.com",         bio:"Senior dermatologist with fellowship training in dermatopathology and skin cancer." },
  { name:"Dr. Sunil Tiwari",       specialty:"Dermatologist", department:"Dermatology", qualification:"MBBS, DVD",                        experience:6,  fee:480,  rating:4.4, email:"sunil.tiwari@docapp.com",        bio:"General dermatologist handling common skin infections, allergies and rashes." },
  { name:"Dr. Lakshmi Reddy",      specialty:"Dermatologist", department:"Dermatology", qualification:"MBBS, MD Dermatology",             experience:14, fee:630,  rating:4.7, email:"lakshmi.reddy@docapp.com",       bio:"Aesthetic dermatologist specialising in botox, fillers and non-surgical face rejuvenation." },
  // ── Neurologists (10) ───────────────────────────────────────────────────────
  { name:"Dr. Suresh Nair",        specialty:"Neurologist", department:"Neurology", qualification:"MBBS, MD, DM Neurology",               experience:20, fee:1000, rating:4.7, email:"suresh.nair@docapp.com",         bio:"Leading neurologist specialising in stroke, epilepsy and neurodegenerative diseases." },
  { name:"Dr. Asha Menon",         specialty:"Neurologist", department:"Neurology", qualification:"MBBS, MD, DM Neurology",               experience:15, fee:950,  rating:4.8, email:"asha.menon@docapp.com",          bio:"Expert in multiple sclerosis, movement disorders and neuroimmunology." },
  { name:"Dr. Prakash Rao",        specialty:"Neurologist", department:"Neurology", qualification:"MBBS, DM Neurology",                   experience:12, fee:900,  rating:4.6, email:"prakash.rao@docapp.com",         bio:"Specialises in headache disorders, migraine management and pain neurology." },
  { name:"Dr. Divya Sharma",       specialty:"Neurologist", department:"Neurology", qualification:"MBBS, MD, DM Neurology",               experience:9,  fee:850,  rating:4.5, email:"divya.sharma@docapp.com",        bio:"Focused on child neurology, developmental disorders and childhood epilepsy." },
  { name:"Dr. Manoj Pillai",       specialty:"Neurologist", department:"Neurology", qualification:"MBBS, DM Neurology, FAAN",             experience:22, fee:1100, rating:4.9, email:"manoj.pillai@docapp.com",        bio:"Fellow of the American Academy of Neurology with expertise in neuromuscular diseases." },
  { name:"Dr. Shalini Verma",      specialty:"Neurologist", department:"Neurology", qualification:"MBBS, MD, DM Neurology",               experience:11, fee:880,  rating:4.7, email:"shalini.verma@docapp.com",       bio:"Specialises in cognitive disorders, dementia and Alzheimer's disease management." },
  { name:"Dr. Rajiv Bose",         specialty:"Neurologist", department:"Neurology", qualification:"MBBS, DM Neurology",                   experience:17, fee:970,  rating:4.8, email:"rajiv.bose@docapp.com",          bio:"Expert in interventional neurology and endovascular treatment of stroke." },
  { name:"Dr. Nisha Kapoor",       specialty:"Neurologist", department:"Neurology", qualification:"MBBS, MD Neurology",                   experience:8,  fee:820,  rating:4.5, email:"nisha.kapoor@docapp.com",        bio:"Neurologist with focus on sleep disorders, narcolepsy and restless leg syndrome." },
  { name:"Dr. Tarun Iyer",         specialty:"Neurologist", department:"Neurology", qualification:"MBBS, MD, DM Neurology",               experience:14, fee:930,  rating:4.7, email:"tarun.iyer@docapp.com",          bio:"Specialises in Parkinson's disease, tremors and deep brain stimulation therapy." },
  { name:"Dr. Geeta Singh",        specialty:"Neurologist", department:"Neurology", qualification:"MBBS, DM Neurology",                   experience:10, fee:860,  rating:4.6, email:"geeta.singh@docapp.com",         bio:"Expert in neuro-ophthalmology and disorders affecting vision from neurological causes." },
  // ── Gynaecologists (10) ─────────────────────────────────────────────────────
  { name:"Dr. Kavitha Reddy",      specialty:"Gynaecologist", department:"Gynaecology", qualification:"MBBS, MS OBG",                     experience:15, fee:700,  rating:4.8, email:"kavitha.reddy@docapp.com",       bio:"Experienced gynaecologist offering comprehensive women's health services and high-risk pregnancy care." },
  { name:"Dr. Usha Patel",         specialty:"Gynaecologist", department:"Gynaecology", qualification:"MBBS, MS OBG, DNB",                experience:20, fee:750,  rating:4.9, email:"usha.patel@docapp.com",          bio:"Senior obstetrician with expertise in high-risk pregnancy and foetal medicine." },
  { name:"Dr. Poornima Nair",      specialty:"Gynaecologist", department:"Gynaecology", qualification:"MBBS, DGO, MS OBG",                experience:12, fee:650,  rating:4.7, email:"poornima.nair@docapp.com",       bio:"Specialises in laparoscopic gynaecological surgery and endometriosis treatment." },
  { name:"Dr. Sujata Kulkarni",    specialty:"Gynaecologist", department:"Gynaecology", qualification:"MBBS, MS OBG",                     experience:17, fee:720,  rating:4.8, email:"sujata.kulkarni@docapp.com",     bio:"Expert in infertility treatment, IVF consultation and reproductive medicine." },
  { name:"Dr. Anita Joshi",        specialty:"Gynaecologist", department:"Gynaecology", qualification:"MBBS, DGO",                        experience:8,  fee:580,  rating:4.5, email:"anita.joshi@docapp.com",         bio:"General gynaecologist handling routine women's health, PCOS and menstrual disorders." },
  { name:"Dr. Rekha Menon",        specialty:"Gynaecologist", department:"Gynaecology", qualification:"MBBS, MS OBG, FRCOG",              experience:25, fee:900,  rating:4.9, email:"rekha.menon@docapp.com",         bio:"Fellow of the Royal College of Obstetricians with 25 years of experience in complex deliveries." },
  { name:"Dr. Sunanda Rao",        specialty:"Gynaecologist", department:"Gynaecology", qualification:"MBBS, MS OBG",                     experience:10, fee:620,  rating:4.6, email:"sunanda.rao@docapp.com",         bio:"Specialises in cervical cancer screening, colposcopy and gynaecologic oncology." },
  { name:"Dr. Bharati Singh",      specialty:"Gynaecologist", department:"Gynaecology", qualification:"MBBS, DGO, MS OBG",                experience:14, fee:680,  rating:4.7, email:"bharati.singh@docapp.com",       bio:"Expert in urogynaecology, pelvic floor disorders and urinary incontinence." },
  { name:"Dr. Chitra Pillai",      specialty:"Gynaecologist", department:"Gynaecology", qualification:"MBBS, MS OBG",                     experience:9,  fee:600,  rating:4.6, email:"chitra.pillai@docapp.com",       bio:"Adolescent gynaecology specialist handling puberty disorders and menstrual problems in teens." },
  { name:"Dr. Meena Sharma",       specialty:"Gynaecologist", department:"Gynaecology", qualification:"MBBS, MS OBG, DNB",                experience:16, fee:730,  rating:4.8, email:"meena.sharma@docapp.com",        bio:"Minimally invasive gynaecological surgeon with expertise in hysteroscopy and fibroid removal." },
  // ── Orthopaedics (10) ───────────────────────────────────────────────────────
  { name:"Dr. Rajan Pillai",       specialty:"Orthopaedic", department:"Orthopaedics", qualification:"MBBS, MS Orthopaedics",             experience:16, fee:750,  rating:4.6, email:"rajan.pillai@docapp.com",        bio:"Specialist in joint replacement, sports injuries and spine surgery." },
  { name:"Dr. Vikram Rao",         specialty:"Orthopaedic", department:"Orthopaedics", qualification:"MBBS, MS Orthopaedics, MCh",        experience:20, fee:850,  rating:4.8, email:"vikram.rao@docapp.com",          bio:"Joint replacement surgeon with over 2000 successful knee and hip replacement procedures." },
  { name:"Dr. Sunil Mehta",        specialty:"Orthopaedic", department:"Orthopaedics", qualification:"MBBS, MS Orthopaedics",             experience:12, fee:700,  rating:4.7, email:"sunil.mehta@docapp.com",         bio:"Sports medicine specialist working with professional athletes and teams." },
  { name:"Dr. Anil Kumar",         specialty:"Orthopaedic", department:"Orthopaedics", qualification:"MBBS, DNB Orthopaedics",            experience:9,  fee:650,  rating:4.5, email:"anil.kumar@docapp.com",          bio:"Specialises in paediatric orthopaedics, club foot and limb deformity corrections." },
  { name:"Dr. Harish Bose",        specialty:"Orthopaedic", department:"Orthopaedics", qualification:"MBBS, MS Orthopaedics",             experience:18, fee:800,  rating:4.8, email:"harish.bose@docapp.com",         bio:"Expert in spine surgery, disc herniation and minimally invasive spinal procedures." },
  { name:"Dr. Pradeep Shetty",     specialty:"Orthopaedic", department:"Orthopaedics", qualification:"MBBS, MS, MCh Orthopaedics",        experience:15, fee:780,  rating:4.7, email:"pradeep.shetty@docapp.com",      bio:"Trauma surgeon specialising in complex fracture management and polytrauma care." },
  { name:"Dr. Girish Iyer",        specialty:"Orthopaedic", department:"Orthopaedics", qualification:"MBBS, MS Orthopaedics",             experience:11, fee:680,  rating:4.6, email:"girish.iyer@docapp.com",         bio:"Arthroscopic surgery specialist for knee, shoulder and ankle joint procedures." },
  { name:"Dr. Mohan Das",          specialty:"Orthopaedic", department:"Orthopaedics", qualification:"MBBS, DNB Orthopaedics",            experience:7,  fee:600,  rating:4.4, email:"mohan.das@docapp.com",           bio:"General orthopaedic surgeon handling musculoskeletal pain and physiotherapy referrals." },
  { name:"Dr. Santosh Verma",      specialty:"Orthopaedic", department:"Orthopaedics", qualification:"MBBS, MS Orthopaedics",             experience:22, fee:900,  rating:4.9, email:"santosh.verma@docapp.com",       bio:"Renowned hand and microsurgery specialist with expertise in tendon and nerve repairs." },
  { name:"Dr. Latha Krishnan",     specialty:"Orthopaedic", department:"Orthopaedics", qualification:"MBBS, MS Orthopaedics",             experience:13, fee:720,  rating:4.7, email:"latha.krishnan@docapp.com",      bio:"Rheumatology-oriented orthopaedic surgeon specialising in arthritis and joint preservation." },
  // ── Paediatricians (10) ─────────────────────────────────────────────────────
  { name:"Dr. Anita Desai",        specialty:"Paediatrician", department:"Paediatrics", qualification:"MBBS, MD Paediatrics",             experience:14, fee:600,  rating:4.9, email:"anita.desai@docapp.com",         bio:"Dedicated paediatrician providing compassionate care for children from birth through adolescence." },
  { name:"Dr. Sunita Pillai",      specialty:"Paediatrician", department:"Paediatrics", qualification:"MBBS, MD Paediatrics, DCH",        experience:18, fee:650,  rating:4.8, email:"sunita.pillai@docapp.com",       bio:"Senior paediatrician with expertise in neonatology and premature infant care." },
  { name:"Dr. Rahul Kapoor",       specialty:"Paediatrician", department:"Paediatrics", qualification:"MBBS, DCH, MD Paediatrics",        experience:10, fee:550,  rating:4.7, email:"rahul.kapoor@docapp.com",        bio:"Paediatric neurologist handling childhood epilepsy, autism and developmental delays." },
  { name:"Dr. Nandita Rao",        specialty:"Paediatrician", department:"Paediatrics", qualification:"MBBS, MD Paediatrics",             experience:8,  fee:520,  rating:4.6, email:"nandita.rao@docapp.com",         bio:"Focused on childhood nutrition, growth disorders and immunisation schedules." },
  { name:"Dr. Arun Shetty",        specialty:"Paediatrician", department:"Paediatrics", qualification:"MBBS, MD Paediatrics, DNB",        experience:12, fee:580,  rating:4.7, email:"arun.shetty@docapp.com",         bio:"Paediatric cardiologist managing congenital heart defects in newborns and children." },
  { name:"Dr. Swati Mehta",        specialty:"Paediatrician", department:"Paediatrics", qualification:"MBBS, DCH",                        experience:6,  fee:480,  rating:4.5, email:"swati.mehta@docapp.com",         bio:"General paediatrician handling common childhood illnesses, infections and fever management." },
  { name:"Dr. Vivek Nair",         specialty:"Paediatrician", department:"Paediatrics", qualification:"MBBS, MD Paediatrics",             experience:15, fee:620,  rating:4.8, email:"vivek.nair@docapp.com",          bio:"Paediatric gastroenterologist treating digestive disorders and food allergies in children." },
  { name:"Dr. Padma Iyer",         specialty:"Paediatrician", department:"Paediatrics", qualification:"MBBS, MD Paediatrics, FIAP",       experience:20, fee:700,  rating:4.9, email:"padma.iyer@docapp.com",          bio:"Fellow of the Indian Academy of Paediatrics with expertise in paediatric critical care." },
  { name:"Dr. Suresh Gupta",       specialty:"Paediatrician", department:"Paediatrics", qualification:"MBBS, DCH, MD",                    experience:9,  fee:540,  rating:4.6, email:"suresh.gupta@docapp.com",        bio:"Adolescent medicine specialist handling teenage health, mental health and puberty issues." },
  { name:"Dr. Asha Bose",          specialty:"Paediatrician", department:"Paediatrics", qualification:"MBBS, MD Paediatrics",             experience:11, fee:560,  rating:4.7, email:"asha.bose@docapp.com",           bio:"Paediatric pulmonologist managing childhood asthma, bronchitis and respiratory disorders." },
  // ── General Physicians (10) ─────────────────────────────────────────────────
  { name:"Dr. Vijay Kumar",        specialty:"General Physician", department:"General Medicine", qualification:"MBBS, MD General Medicine",  experience:10, fee:400,  rating:4.5, email:"vijay.kumar@docapp.com",         bio:"General physician offering primary care, preventive medicine and chronic disease management." },
  { name:"Dr. Ramya Shetty",       specialty:"General Physician", department:"General Medicine", qualification:"MBBS, MD Internal Medicine", experience:14, fee:450,  rating:4.7, email:"ramya.shetty@docapp.com",        bio:"Internist with expertise in managing hypertension, diabetes and lifestyle diseases." },
  { name:"Dr. Arun Pillai",        specialty:"General Physician", department:"General Medicine", qualification:"MBBS, MD",                   experience:8,  fee:380,  rating:4.5, email:"arun.pillai@docapp.com",         bio:"Family medicine specialist handling acute illnesses, vaccinations and routine checkups." },
  { name:"Dr. Shobha Nair",        specialty:"General Physician", department:"General Medicine", qualification:"MBBS, MD General Medicine",  experience:16, fee:480,  rating:4.8, email:"shobha.nair@docapp.com",         bio:"Senior internist experienced in complex multi-system diseases and geriatric medicine." },
  { name:"Dr. Prasad Rao",         specialty:"General Physician", department:"General Medicine", qualification:"MBBS, MD",                   experience:12, fee:420,  rating:4.6, email:"prasad.rao@docapp.com",          bio:"Travel medicine and infectious disease specialist for international travellers." },
  { name:"Dr. Kavita Joshi",       specialty:"General Physician", department:"General Medicine", qualification:"MBBS, MD Internal Medicine", experience:9,  fee:400,  rating:4.6, email:"kavita.joshi@docapp.com",        bio:"Provides holistic primary care including preventive health counselling and screenings." },
  { name:"Dr. Santosh Iyer",       specialty:"General Physician", department:"General Medicine", qualification:"MBBS, MD",                   experience:20, fee:500,  rating:4.9, email:"santosh.iyer@docapp.com",        bio:"Highly experienced internist known for accurate diagnosis of rare and complex conditions." },
  { name:"Dr. Deepa Menon",        specialty:"General Physician", department:"General Medicine", qualification:"MBBS, MD General Medicine",  experience:7,  fee:370,  rating:4.4, email:"deepa.menon@docapp.com",         bio:"Dedicated to patient education, preventive care and evidence-based medicine." },
  { name:"Dr. Rakesh Sharma",      specialty:"General Physician", department:"General Medicine", qualification:"MBBS, MD",                   experience:11, fee:410,  rating:4.6, email:"rakesh.sharma@docapp.com",       bio:"Specialises in occupational health, workplace injuries and corporate wellness programmes." },
  { name:"Dr. Usha Kapoor",        specialty:"General Physician", department:"General Medicine", qualification:"MBBS, MD Internal Medicine", experience:15, fee:460,  rating:4.7, email:"usha.kapoor@docapp.com",         bio:"Internal medicine specialist with a focus on anaemia, thyroid and metabolic disorders." },
  // ── Ophthalmologists (10) ───────────────────────────────────────────────────
  { name:"Dr. Meena Joshi",        specialty:"Ophthalmologist", department:"Ophthalmology", qualification:"MBBS, MS Ophthalmology",          experience:13, fee:650,  rating:4.7, email:"meena.joshi2@docapp.com",        bio:"Eye specialist with expertise in cataract surgery, glaucoma treatment and retinal disorders." },
  { name:"Dr. Harsha Bhat",        specialty:"Ophthalmologist", department:"Ophthalmology", qualification:"MBBS, MS Ophthalmology, DNB",     experience:17, fee:700,  rating:4.8, email:"harsha.bhat@docapp.com",         bio:"Retinal surgeon specialising in diabetic retinopathy and macular degeneration." },
  { name:"Dr. Preethi Rao",        specialty:"Ophthalmologist", department:"Ophthalmology", qualification:"MBBS, MS Ophthalmology",          experience:9,  fee:600,  rating:4.6, email:"preethi.rao@docapp.com",         bio:"Expert in LASIK and refractive surgery for glasses-free vision correction." },
  { name:"Dr. Srinivas Iyer",      specialty:"Ophthalmologist", department:"Ophthalmology", qualification:"MBBS, DO, MS Ophthalmology",      experience:22, fee:750,  rating:4.9, email:"srinivas.iyer@docapp.com",       bio:"Senior eye surgeon with 2500+ cataract surgeries and fellowship in corneal transplants." },
  { name:"Dr. Anita Pillai",       specialty:"Ophthalmologist", department:"Ophthalmology", qualification:"MBBS, MS Ophthalmology",          experience:10, fee:620,  rating:4.6, email:"anita.pillai@docapp.com",        bio:"Paediatric ophthalmologist treating squint, lazy eye and childhood vision problems." },
  { name:"Dr. Mohan Verma",        specialty:"Ophthalmologist", department:"Ophthalmology", qualification:"MBBS, MS Ophthalmology",          experience:14, fee:660,  rating:4.7, email:"mohan.verma@docapp.com",         bio:"Glaucoma specialist with expertise in trabeculectomy and advanced pressure management." },
  { name:"Dr. Savitha Nair",       specialty:"Ophthalmologist", department:"Ophthalmology", qualification:"MBBS, DO, MS",                    experience:8,  fee:580,  rating:4.5, email:"savitha.nair@docapp.com",        bio:"Contact lens specialist and optometry consultant for complex refractive errors." },
  { name:"Dr. Kamal Shetty",       specialty:"Ophthalmologist", department:"Ophthalmology", qualification:"MBBS, MS Ophthalmology",          experience:18, fee:720,  rating:4.8, email:"kamal.shetty@docapp.com",        bio:"Oculoplastics surgeon handling eyelid disorders, ptosis and orbital tumours." },
  { name:"Dr. Jyothi Menon",       specialty:"Ophthalmologist", department:"Ophthalmology", qualification:"MBBS, MS Ophthalmology, FICO",    experience:12, fee:640,  rating:4.7, email:"jyothi.menon@docapp.com",        bio:"Fellow of the International Council of Ophthalmology with expertise in uveitis." },
  { name:"Dr. Sunil Bose",         specialty:"Ophthalmologist", department:"Ophthalmology", qualification:"MBBS, MS Ophthalmology",          experience:7,  fee:560,  rating:4.4, email:"sunil.bose@docapp.com",          bio:"General ophthalmologist providing comprehensive eye care and spectacle prescriptions." },
  // ── ENT Specialists (10) ────────────────────────────────────────────────────
  { name:"Dr. Sameer Kapoor",      specialty:"ENT Specialist", department:"ENT", qualification:"MBBS, MS ENT",                              experience:11, fee:550,  rating:4.6, email:"sameer.kapoor@docapp.com",       bio:"ENT surgeon treating disorders of ear, nose and throat including hearing loss and sinus conditions." },
  { name:"Dr. Padmaja Rao",        specialty:"ENT Specialist", department:"ENT", qualification:"MBBS, MS ENT, DNB",                         experience:15, fee:600,  rating:4.7, email:"padmaja.rao@docapp.com",         bio:"Head and neck surgeon specialising in thyroid surgeries and salivary gland tumours." },
  { name:"Dr. Karthik Nair",       specialty:"ENT Specialist", department:"ENT", qualification:"MBBS, MS ENT",                              experience:9,  fee:520,  rating:4.5, email:"karthik.nair@docapp.com",        bio:"Cochlear implant surgeon and hearing rehabilitation specialist for profound deafness." },
  { name:"Dr. Smita Pillai",       specialty:"ENT Specialist", department:"ENT", qualification:"MBBS, DLO, MS ENT",                         experience:13, fee:570,  rating:4.7, email:"smita.pillai@docapp.com",        bio:"Paediatric ENT specialist treating tonsillitis, adenoids and ear infections in children." },
  { name:"Dr. Rajesh Iyer",        specialty:"ENT Specialist", department:"ENT", qualification:"MBBS, MS ENT",                              experience:20, fee:650,  rating:4.8, email:"rajesh.iyer@docapp.com",         bio:"Rhinologist with expertise in endoscopic sinus surgery and nasal polyp management." },
  { name:"Dr. Nirmala Shetty",     specialty:"ENT Specialist", department:"ENT", qualification:"MBBS, MS ENT",                              experience:8,  fee:500,  rating:4.5, email:"nirmala.shetty@docapp.com",      bio:"Laryngologist specialising in voice disorders, vocal cord polyps and laryngoscopy." },
  { name:"Dr. Aravind Kumar",      specialty:"ENT Specialist", department:"ENT", qualification:"MBBS, MS ENT, FACS",                        experience:17, fee:620,  rating:4.8, email:"aravind.kumar@docapp.com",       bio:"Fellow of the American College of Surgeons specialising in skull base and otology surgeries." },
  { name:"Dr. Leela Menon",        specialty:"ENT Specialist", department:"ENT", qualification:"MBBS, DLO, MS",                             experience:12, fee:550,  rating:4.6, email:"leela.menon@docapp.com",         bio:"Allergy and immunology-oriented ENT specialist handling chronic sinusitis and rhinitis." },
  { name:"Dr. Suhas Rao",          specialty:"ENT Specialist", department:"ENT", qualification:"MBBS, MS ENT",                              experience:6,  fee:480,  rating:4.4, email:"suhas.rao@docapp.com",           bio:"General ENT surgeon managing common ear, nose and throat conditions and minor procedures." },
  { name:"Dr. Vani Krishnan",      specialty:"ENT Specialist", department:"ENT", qualification:"MBBS, MS ENT",                              experience:14, fee:590,  rating:4.7, email:"vani.krishnan@docapp.com",       bio:"Sleep medicine ENT specialising in snoring, sleep apnoea and CPAP therapy." },
  // ── Endocrinologists (10) ───────────────────────────────────────────────────
  { name:"Dr. Lakshmi Iyer",       specialty:"Endocrinologist", department:"Endocrinology", qualification:"MBBS, MD, DM Endocrinology",      experience:17, fee:900,  rating:4.8, email:"lakshmi.iyer@docapp.com",        bio:"Specialist in diabetes, thyroid disorders and hormonal imbalances with a patient-centric approach." },
  { name:"Dr. Rajiv Menon",        specialty:"Endocrinologist", department:"Endocrinology", qualification:"MBBS, MD, DM Endocrinology",      experience:20, fee:950,  rating:4.9, email:"rajiv.menon@docapp.com",         bio:"Expert in Type 1 and Type 2 diabetes management including insulin pump therapy." },
  { name:"Dr. Geetha Pillai",      specialty:"Endocrinologist", department:"Endocrinology", qualification:"MBBS, MD, DM Endocrinology",      experience:13, fee:850,  rating:4.7, email:"geetha.pillai@docapp.com",       bio:"Thyroid cancer specialist handling thyroidectomy referrals and radioactive iodine therapy." },
  { name:"Dr. Sunder Rao",         specialty:"Endocrinologist", department:"Endocrinology", qualification:"MBBS, DM Endocrinology",          experience:9,  fee:800,  rating:4.6, email:"sunder.rao@docapp.com",          bio:"Metabolic disorder specialist managing obesity, insulin resistance and PCOS." },
  { name:"Dr. Priya Bose",         specialty:"Endocrinologist", department:"Endocrinology", qualification:"MBBS, MD, DM Endocrinology",      experience:15, fee:880,  rating:4.8, email:"priya.bose@docapp.com",          bio:"Paediatric endocrinologist treating growth hormone deficiency and early puberty in children." },
  { name:"Dr. Naresh Sharma",      specialty:"Endocrinologist", department:"Endocrinology", qualification:"MBBS, DM Endocrinology",          experience:11, fee:820,  rating:4.7, email:"naresh.sharma@docapp.com",       bio:"Adrenal gland specialist managing Cushing's syndrome, Addison's disease and phaeochromocytoma." },
  { name:"Dr. Meera Nair",         specialty:"Endocrinologist", department:"Endocrinology", qualification:"MBBS, MD, DM Endocrinology",      experience:18, fee:930,  rating:4.8, email:"meera.nair@docapp.com",          bio:"Reproductive endocrinologist specialising in PCOS, infertility and menopause management." },
  { name:"Dr. Ajay Kapoor",        specialty:"Endocrinologist", department:"Endocrinology", qualification:"MBBS, DM Endocrinology",          experience:8,  fee:780,  rating:4.5, email:"ajay.kapoor@docapp.com",         bio:"Focuses on bone metabolism, osteoporosis prevention and vitamin D deficiency management." },
  { name:"Dr. Sudha Iyer",         specialty:"Endocrinologist", department:"Endocrinology", qualification:"MBBS, MD, DM Endocrinology",      experience:22, fee:1000, rating:4.9, email:"sudha.iyer@docapp.com",          bio:"Pioneer in diabetes technology including continuous glucose monitors and closed-loop systems." },
  { name:"Dr. Kishore Menon",      specialty:"Endocrinologist", department:"Endocrinology", qualification:"MBBS, DM Endocrinology",          experience:10, fee:810,  rating:4.6, email:"kishore.menon@docapp.com",       bio:"Pituitary gland specialist managing growth hormone excess, prolactinomas and Cushing's disease." },
];

// ── Seed ──────────────────────────────────────────────────────────────────────
router.post("/seed", async (req, res) => {
  try {
    const [existing] = await pool.query("SELECT id FROM doctors LIMIT 1");
    if (existing.length) return res.json({ message: "Already seeded" });

    for (const doc of SEED_DOCTORS) {
      const [result] = await pool.query(
        "INSERT INTO doctors (name,specialty,department,qualification,experience,fee,email,bio,rating) VALUES (?,?,?,?,?,?,?,?,?)",
        [doc.name, doc.specialty, doc.department, doc.qualification, doc.experience, doc.fee, doc.email, doc.bio, doc.rating]
      );
      for (const day of DAYS) {
        await pool.query(
          "INSERT INTO doctor_availability (doctor_id, day, times) VALUES (?,?,?)",
          [result.insertId, day, TIMES]
        );
      }
    }

    const [adminExists] = await pool.query("SELECT id FROM users WHERE role='admin' LIMIT 1");
    if (!adminExists.length) {
      const hashed = await bcrypt.hash("admin123", 10);
      await pool.query("INSERT INTO users (name,email,password,role) VALUES (?,?,?,?)", ["Admin","admin@docapp.com",hashed,"admin"]);
    }

    res.json({ message:`Seeded ${SEED_DOCTORS.length} doctors and admin account`, adminEmail:"admin@docapp.com", adminPassword:"admin123" });
  } catch (err) { res.status(500).json({ message: err.message }); }
});

// ── Stats ─────────────────────────────────────────────────────────────────────
router.get("/stats", adminOnly, async (req, res) => {
  try {
    const [[{ totalPatients }]]     = await pool.query("SELECT COUNT(*) AS totalPatients FROM users WHERE role='patient'");
    const [[{ totalDoctors }]]      = await pool.query("SELECT COUNT(*) AS totalDoctors FROM doctors WHERE is_active=1");
    const [[{ totalAppointments }]] = await pool.query("SELECT COUNT(*) AS totalAppointments FROM appointments");
    const today                     = new Date().toISOString().slice(0,10);
    const [[{ todayCount }]]        = await pool.query("SELECT COUNT(*) AS todayCount FROM appointments WHERE date=?", [today]);
    const [statusCounts]            = await pool.query("SELECT status AS _id, COUNT(*) AS count FROM appointments GROUP BY status");
    res.json({ totalPatients, totalDoctors, totalAppointments, todayCount, statusCounts });
  } catch (err) { res.status(500).json({ message: err.message }); }
});

// ── Patients ──────────────────────────────────────────────────────────────────
router.get("/patients", adminOnly, async (req, res) => {
  try {
    const [rows] = await pool.query("SELECT id,name,email,phone,dob,gender,address,created_at FROM users WHERE role='patient' ORDER BY created_at DESC");
    res.json(rows);
  } catch (err) { res.status(500).json({ message: err.message }); }
});

module.exports = router;